credentials:
  usernames:
    admin:
      name: Quản trị viên
      password: "123"
    user1:
      name: Giáo viên 1
      email: user1@example.com
      password: pass123
preauthorized:
  emails:
    - user1@example.com